### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'

### ISSUE THREAD

**Issue by clwclw123** [jdholtz/auto-southwest-check-in#181]
### Version

Auto-Southwest Check-In v7.0

### Browser Version

119.0.6045.124 (Brave)

### Description

Tried checking in with my SWA credentials after updating to 7.0

### To Reproduce

I ran:

`PS C:\Users\root\Desktop\auto-southwest-check-in> python3 southwest.py MYLOGIN P@SSW0RD --verbose`

### Relevant logs and program output

```sh
2023-11-10 07:41:45 DEBUG MainProcess[log:23]: Initialized the application
2023-11-10 07:41:45 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.0
2023-11-10 07:41:45 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-11-10 07:41:46 DEBUG MainProcess[config:107]: Initializing configuration file
2023-11-10 07:41:46 DEBUG MainProcess[config:135]: Reading the configuration file
2023-11-10 07:41:46 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-11-10 07:41:46 DEBUG MainProcess[config:118]: Creating configurations for 1 accounts
2023-11-10 07:41:46 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-11-10 07:41:46 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-11-10 07:41:48 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-11-10 07:41:48 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-11-10 07:41:48 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-11-10 07:41:48 DEBUG Process-1[webdriver:102]: Starting webdriver for current session

Warning: uc_driver not found. Getting it now:

DevTools listening on ws://127.0.0.1:53651/devtools/browser/cd6b45a3-f05e-4163-bf91-e89af1298aeb
2023-11-10 07:41:54 DEBUG Process-1[webdriver:111]: Using browser version: 119.0.6045.124
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\root\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "C:\Users\root\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\root\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\root\Desktop\auto-southwest-check-in\lib\webdriver.py", line 76, in get_reservations
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\root\Desktop\auto-southwest-check-in\lib\webdriver.py", line 113, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
Press any key to continue . . .
```

### Additional context

Windows 10
Python 3.11.6 (Windows Store)

**Comment by jdholtz** [comment]
This is a duplicate of #180 where the Chromedriver version isn’t available for the browser version you have. Can you try on the latest commit of the develop branch (run `git pull && git checkout develop && pip install -r requirements.txt`)?

**Comment by jdholtz** [comment]
> if I run the script a week or two early, will it continue to retry until the check-in date?

By default, it sleeps once a day in between checking your account for new flights or lower fares for any currently scheduled flights. To disable this, you can configure the retrieval_interval to be 0 (see the configuration documentation for more information).

As for scheduling flights, the script will put the flight into a separate process and have it sleep until check-in time. It sleeps in 2 week increments to prevent an overflow in sleep time. Therefore, you can run the script whenever you want (you can even have it run forever).
